[package]
name = "say-hello"
version = "0.1.0"
edition = "2021"
description = "This just test bro"
license = "Apache-2.0"
authors = ["Yogi"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
